import { RsvpRecord, calculateHeadcount } from "../types/rsvp";

const createMockRecord = (
  id: string,
  guestFullName: string,
  email: string,
  phone: string,
  isAttending: boolean,
  hasPlusOne: boolean,
  plusOneName: string,
  children: { id: string; age: number; gender: "male" | "female" }[],
  hasNanny: boolean,
  nannyCount: number,
  dietaryNotes: string,
  messageToCelebrant: string,
  checkedIn: boolean = false,
  checkedInAt: string | null = null,
  actualHeadcount: number | null = null
): RsvpRecord => {
  const formValues = {
    guestFullName,
    email,
    phone,
    isAttending,
    hasPlusOne,
    plusOneName,
    children,
    hasNanny,
    nannyCount,
    dietaryNotes,
    messageToCelebrant,
  };

  const totalHeadcount = calculateHeadcount(formValues);

  return {
    id,
    ...formValues,
    createdAt: new Date(Date.now() - Math.floor(Math.random() * 10) * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    totalHeadcount,
    checkedIn,
    checkedInAt,
    actualHeadcount: checkedIn ? (actualHeadcount ?? totalHeadcount) : null,
  };
};

export const MOCK_RSVPS: RsvpRecord[] = [
  createMockRecord(
    "rsvp-001",
    "Akinola Adebayo",
    "akin.adebayo@gmail.com",
    "+2348023456781",
    true,
    true,
    "Funmi Adebayo",
    [
      { id: "c1", age: 7, gender: "male" },
      { id: "c2", age: 5, gender: "female" },
    ],
    true,
    1,
    "Peanut allergy for older child",
    "Happy 7th Birthday Zion! Excited to celebrate with you!",
    true,
    "2026-10-18T14:15:00+01:00",
    5
  ),
  createMockRecord(
    "rsvp-002",
    "Chinedu Okonkwo",
    "chinedu.o@yahoo.com",
    "+2348039876543",
    true,
    false,
    "",
    [
      { id: "c3", age: 6, gender: "male" },
      { id: "c4", age: 8, gender: "male" },
      { id: "c5", age: 3, gender: "female" },
    ],
    true,
    1,
    "No pork / Halal only please",
    "Zion, get ready for superhero games! Happy Birthday buddy!",
    true,
    "2026-10-18T14:30:00+01:00",
    5
  ),
  createMockRecord(
    "rsvp-003",
    "Folake Balogun",
    "fbalogun@outlook.com",
    "+2348123459988",
    true,
    true,
    "Tunde Balogun",
    [{ id: "c6", age: 7, gender: "female" }],
    false,
    0,
    "Gluten sensitivity",
    "Can't wait for Zion's big day! Wishing him joy and strength!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-004",
    "Emeka Nwosu",
    "emeka.nwosu@gmail.com",
    "+2348051122334",
    true,
    false,
    "",
    [
      { id: "c7", age: 4, gender: "male" },
      { id: "c8", age: 9, gender: "female" },
    ],
    false,
    0,
    "",
    "Happy 7th Birthday Champion Zion!",
    true,
    "2026-10-18T14:05:00+01:00",
    3
  ),
  createMockRecord(
    "rsvp-005",
    "Bisi Ogundipe",
    "bisi.ogundipe@live.com",
    "+2348098877665",
    false,
    false,
    "",
    [],
    false,
    0,
    "",
    "So sorry we will be out of town. Sending Zion lots of love and birthday hugs!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-006",
    "Kemi Danjuma",
    "kemi.d@danjumagroup.com",
    "+2348145566778",
    true,
    true,
    "Kabir Danjuma",
    [
      { id: "c9", age: 7, gender: "male" },
      { id: "c10", age: 10, gender: "female" },
      { id: "c11", age: 2, gender: "male" },
      { id: "c12", age: 12, gender: "female" },
    ],
    true,
    2,
    "Lactose intolerant for the youngest",
    "Super excited! See you guys soon!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-007",
    "Toluwalase Soyinka",
    "tolu.soyinka@gmail.com",
    "+2348187766554",
    true,
    false,
    "",
    [{ id: "c13", age: 6, gender: "female" }],
    false,
    0,
    "Vegetarian",
    "Happy Birthday Zion! May your year be filled with epic adventures!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-008",
    "Dr. Olamide Lawson",
    "olamide.lawson@health.ng",
    "+2348021133557",
    true,
    true,
    "Dr. Yemi Lawson",
    [
      { id: "c14", age: 7, gender: "male" },
      { id: "c15", age: 5, gender: "male" },
    ],
    true,
    1,
    "",
    "Big 7! Happy Birthday Zion from the Lawson family!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-009",
    "Ngozi Ezekwesili",
    "ngozi.e@gmail.com",
    "+2348034455667",
    false,
    false,
    "",
    [],
    false,
    0,
    "",
    "Wishing Zion a wonderful 7th birthday celebration!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-010",
    "Babajide Sanwo",
    "jide.sanwo@gmail.com",
    "+2348130099887",
    true,
    true,
    "Titilayo Sanwo",
    [{ id: "c16", age: 7, gender: "male" }],
    false,
    0,
    "",
    "Happy Birthday Zion! Looking forward to face painting and games!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-011",
    "Zainab Ibrahim",
    "zainab.ibrahim@yahoo.com",
    "+2348076655443",
    true,
    false,
    "",
    [
      { id: "c17", age: 6, gender: "female" },
      { id: "c18", age: 4, gender: "male" },
    ],
    true,
    1,
    "Egg allergy",
    "Happy Birthday Zion! See you at 2 PM!",
    false,
    null,
    null
  ),
  createMockRecord(
    "rsvp-012",
    "Dayo Amusan",
    "dayo.amusan@hotmail.com",
    "+2348154433221",
    true,
    true,
    "Nike Amusan",
    [{ id: "c19", age: 7, gender: "female" }],
    false,
    0,
    "",
    "Hero party time! Happy 7th Birthday Zion!",
    false,
    null,
    null
  ),
];
