export const eventConfig = {
  celebrant: { name: "Zion", fullName: "Zion Awolowo", age: 7, photoUrl: "/images/celebrant.jpg" },
  event: {
    title: "Zion's 7th Birthday Spider-Verse Celebration",
    date: "2026-10-18T14:00:00+01:00",
    dateDisplay: "Saturday, October 18th, 2026",
    timeDisplay: "2:00 PM - 7:00 PM",
    venueName: "SPIDER HQ (SECRET VENUE)",
    venueAddress: "PLACEHOLDER ADDRESS, Lagos, Nigeria",
    googleMapsUrl: "https://maps.google.com/?q=PLACEHOLDER",
    dressCode: "Suit up in your favourite Spider-Man suit or Superhero costume!",
    rsvpDeadline: "2026-09-30T23:59:59+01:00",
    rsvpDeadlineDisplay: "September 30th, 2026",
  },
  host: { contactName: "Saidat", contactPhone: "+2348139927805", whatsappNumber: "2348139927805" },
  copy: {
    welcomeHeadline: "SPIDER-SENSE IS TINGLING!",
    welcomeSubtext: "Calling all Web-Slingers & Heroes to Zion's Secret Headquarters!",
    giftNote: "Your presence is the only web-tastic present we need!",
  },
  activities: [
    "🕷️ Web Shooter Training",
    "🎂 Spider-Man Cake Cut",
    "🏃 Spider Obstacle Course",
    "🎨 Face Painting & Masks",
    "📸 Superhero Photo Booth",
    "🎁 Web-Slinger Party Bags",
  ],
  faqs: [
    { q: "Do kids need to wear Spider-Man costumes?", a: "Costumes are super encouraged! Whether it's classic Spidey, Miles Morales, Spider-Gwen, or any hero suit — come ready to swing into action!" },
    { q: "Can I bring my nanny or extra caretaker?", a: "Yes — just list them in the RSVP form so we can prepare their Spider HQ pass." },
    { q: "Should parents stay or drop off?", a: "Parents are very welcome to stay in the Heroes Lounge! There will be comfortable seating and refreshments." },
    { q: "What should we bring to Spider HQ?", a: "Just bring your hero energy! Your presence is the greatest present." },
    { q: "How do I update my RSVP?", a: "You can update it anytime using the link in your confirmation email or by messaging Saidat directly on WhatsApp." },
  ],
  theme: {
    heroRed: "#E23636",
    spideyRed: "#E62429",
    heroBlue: "#114593",
    spideyBlue: "#154785",
    spiderBlack: "#0B0E14",
    ink: "#111111",
    newsprint: "#FDF6E3",
    popPink: "#FF4081",
    popCyan: "#00AEEF",
    popYellow: "#FFD700",
    spiderSenseOrange: "#FF5722",
  },
  agency: { name: "FlagIQ", url: "https://flagiq.org" },
} as const;
